// Code generated by protoc-gen-go. DO NOT EDIT.
// source: packet.proto

/*
Package urpc is a generated protocol buffer package.

It is generated from these files:
	packet.proto

It has these top-level messages:
	RawPacket
*/
package urpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RawPacket struct {
	Cmd         uint32 `protobuf:"varint,1,opt,name=cmd" json:"cmd,omitempty"`
	PayloadSize uint32 `protobuf:"varint,2,opt,name=payload_size,json=payloadSize" json:"payload_size,omitempty"`
	Payload     []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *RawPacket) Reset()                    { *m = RawPacket{} }
func (m *RawPacket) String() string            { return proto.CompactTextString(m) }
func (*RawPacket) ProtoMessage()               {}
func (*RawPacket) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RawPacket) GetCmd() uint32 {
	if m != nil {
		return m.Cmd
	}
	return 0
}

func (m *RawPacket) GetPayloadSize() uint32 {
	if m != nil {
		return m.PayloadSize
	}
	return 0
}

func (m *RawPacket) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*RawPacket)(nil), "urpc.RawPacket")
}

func init() { proto.RegisterFile("packet.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 114 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x48, 0x4c, 0xce,
	0x4e, 0x2d, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x29, 0x2d, 0x2a, 0x48, 0x56, 0x8a,
	0xe2, 0xe2, 0x0c, 0x4a, 0x2c, 0x0f, 0x00, 0x4b, 0x08, 0x09, 0x70, 0x31, 0x27, 0xe7, 0xa6, 0x48,
	0x30, 0x2a, 0x30, 0x6a, 0xf0, 0x06, 0x81, 0x98, 0x42, 0x8a, 0x20, 0x4d, 0x95, 0x39, 0xf9, 0x89,
	0x29, 0xf1, 0xc5, 0x99, 0x55, 0xa9, 0x12, 0x4c, 0x60, 0x29, 0x6e, 0xa8, 0x58, 0x70, 0x66, 0x55,
	0xaa, 0x90, 0x04, 0x17, 0x3b, 0x94, 0x2b, 0xc1, 0xac, 0xc0, 0xa8, 0xc1, 0x13, 0x04, 0xe3, 0x26,
	0xb1, 0x81, 0x2d, 0x32, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xa7, 0x67, 0x30, 0x21, 0x78, 0x00,
	0x00, 0x00,
}
